# ETAPA 1: Construcción (Build)
# Usamos una imagen con Maven y Java 21
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# ETAPA 2: Ejecución (Run)
# Usamos Java 21 ligero para correr la app
FROM eclipse-temurin:21-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Puerto
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]