# ETAPA 1: Construcción (Build)
# Usamos una imagen que ya tiene Maven instalado para compilar tu código
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# ETAPA 2: Ejecución (Run)
# Usamos una imagen ligera de Java 17 para correr la app
FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

# Le decimos a Render que use el puerto 8080
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]